### ISSUE TITLE
Out of Region 3DS game updater?

### ISSUE THREAD

**Issue by rpalmon** [smealum/regionFOUR#10]
Can someone make a homebrew application so that we can update an out of region game that takes data from nintendo's servers and installs the update? I figured that this would be a good place to ask as this is a region free based homebrew application. I would like that so I can play online on some Japanese games that require the latest updates.

**Comment by yellows8** [comment]
That's exactly the same as asking for other-region-eShop-access from userland-only, so no.

**Comment by rpalmon** [comment]
Instead of making a home brew application, How about making a PC program so that I could update 3DS roms as most of the roms I download are outdated?

**Comment by yellows8** [comment]
This is not the place for warez either.

**Comment by urherenow** [comment]
Updates, in and of themselves, are not warez. They don't do any good without the rest of the game installed or the cart.

Funkycia already works for this though.

**Comment by yellows8** [comment]
@urherenow  "update 3DS _roms_"
