### ISSUE TITLE
Open HOME Menu when playing Japanese games?

### ISSUE THREAD

**Issue by rpalmon** [smealum/regionFOUR#11]
Hello,

Why can't I open the HOME Menu when I play Japanese games? When I played a European game I was able to go to the HOME Menu. Can you explain this?

**Comment by smealum** [comment]
yeah basically home menu knows it's not supposed to be running a japanese game so when you open it it kind of freaks out and kills itself.

at least thats my guess i never actually tried to debug it. if you want to exit back to home menu you can press the power button and then hit home. of course doing that will close your game so be sure to save first.

**Comment by rpalmon** [comment]
It's weird that when I play UK games it lets me go to the HOME Menu. Example, when I played Kirby Planet Robobot from the UK it let me go to the HOME Menu. And when I put the cartridge in the system it showed up as a game on the menu.
