### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by ghost** [smealum/regionFOUR#5]
In "cn_secondary_payload/source/main.c" when --enableotherapp is selected ...
# ifndef OTHERAPP
# include "cn_save_initial_loader_bin.h"
# endif

... shouldn't this include not be included?

**Comment by yellows8** [comment]
It only gets included when OTHERAPP isn't used.

And I did test building with OTHERAPP and without it, with that last commit.

**Comment by ghost** [comment]
Are the correctly built payloads about 5KBs?

**Comment by yellows8** [comment]
Yes.

**Comment by ghost** [comment]
Ok, all I can tell you is that it only works if I manually comment out the include when I use --enableotherapp. It gives a "can't find cn_save_initial_loader_bin.h" error if don't.

No big deal but I thought it was important enough to mention.

**Comment by ghost** [comment]
It's a python issue. When I enter:
make CNVERSION=WEST ROVERSION=4096 SPIDERVERSION=4096 FIRMVERSION=POST5 MENUVERSION=12288 OTHERAPP=1
to the root makefile directly for instance, everything works as it should.

So I guess we can chalk this up to a problem on my end, but using python to build things probably isn't the best idea.

**Comment by yellows8** [comment]
Works fine for me(just now tested it again), what command were you using for running the py script?

**Comment by ghost** [comment]
python scripts/buildVersion.py "N9.8.0-25J" --enableotherapp

or

py -3 scripts/buildVersion.py "N9.8.0-25J" --enableotherapp
same result (win 7)

**Comment by yellows8** [comment]
That ifndef line is triggering with and without --enableotherapp, not sure why.

EDIT: The cn_secondary_payload Makefile "@$(CC) -MM" line which doesn't use $(CFLAGS) is causing it.

**Comment by yellows8** [comment]
Fixed: https://github.com/smealum/regionFOUR/commit/6bc1eae25ca891220d6016b044df849ffc0244a7
